-- AlterTable
ALTER TABLE "Camera" ADD COLUMN "protocol" TEXT NOT NULL DEFAULT 'ONVIF';
ALTER TABLE "Camera" ADD COLUMN "rtspPort" INTEGER NOT NULL DEFAULT 554;
ALTER TABLE "Camera" ADD COLUMN "channel" INTEGER NOT NULL DEFAULT 1;
